### ISSUE TITLE
utility is not functioning in Win 8.1

### ISSUE THREAD

**Issue by cdelaney585** [maxmind/geoip2-csv-converter#1]
I am not able to get the utility to run in win 8.1- it just closes immediately. Apologies for not having any more specific information!

**Comment by oschwald** [comment]
This is a command line utility. Are you running it from cmd or PowerShell?

**Comment by oschwald** [comment]
Closing due lack of information.

**Comment by danielp3011** [comment]
Hi there, I have the same problem. I tried cmd and PowerShell. In both the window pops up and closes immediatly again.
Hope somebody can help! :)

**Comment by oschwald** [comment]
This is not a GUI application. You should run it from an interactive terminal. Presumably it is displaying the help info and exiting in your case.

**Comment by danielp3011** [comment]
@oschwald 
Thanks a lot for your fast answer. I'm not shure if I totally understand you. What do you mean by interactive terminal? I tried CMD and Powershall, aren't these interactive terminals?

**Comment by oschwald** [comment]
Can you be more specific about how you are running it? It sounds like you are just double clicking the binary, perhaps after setting run in Powershell in the context dialog. You should run Powershell (or cmd), navigate to the directory, and run `geoip2-csv-converter`. It will then print out the help info.

**Comment by danielp3011** [comment]
@oschwald Do you have some ideas what could be the problem?
