### ISSUE TITLE
Example for csv to mmdb

### ISSUE THREAD

**Issue by mhf-ir** [maxmind/geoip2-csv-converter#17]
Is there any example for csv to mmdb covert?

I need to write CD/CI dev/ops and need to change mmdb for local ips like 10.0.0.x or 192.168.1.x for special data just for testing act of our infrastructure.

**Comment by oschwald** [comment]
Although it isn't exactly what you are looking for, you could start with https://blog.maxmind.com/2015/09/29/building-your-own-mmdb-database-for-fun-and-profit/.
