### ISSUE TITLE
Invalid CIDR address

### ISSUE THREAD

**Issue by danchello** [maxmind/geoip2-csv-converter#25]
v1.1.0 MacOs
 
I am receiving the following error:
`Error: error parsing network (5819): invalid CIDR address: 5819`

Command:
`./geoip2-csv-converter -block-file=GeoLite2-City-Locations-en.csv -output-file=blocks.csv -include-integer-range`

I am using GeoLite2 City: CSV Format (updated 2020-06-30). Any ideas why this is happening?

**Comment by klp2** [comment]
I think the argument to `-block-file` should be either `GeoLite2-City-Blocks-IPv4.csv` or `GeoLite2-City-Blocks-IPv6.csv`

**Comment by danchello** [comment]
> I think the argument to `-block-file` should be either `GeoLite2-City-Blocks-IPv4.csv` or `GeoLite2-City-Blocks-IPv6.csv`

Omg, you are right.
