### ISSUE TITLE
Convert city database

### ISSUE THREAD

**Issue by nimasdj** [maxmind/geoip2-csv-converter#3]
I want to use City database here http://dev.maxmind.com/geoip/geoip2/geoip2-csv-databases/ as input file. Is that a valid input file for this converter or input file needs to have only one CIDR column and nothing else? If this is valid, does this convertermove other columns of City database to output file too?

**Comment by oschwald** [comment]
The input file should be a GeoIP2 block file, as distributed with the CSV. Please direct support questions to `support@maxmind.com`.

**Comment by nimasdj** [comment]
Please calrify 1) does this converter accept City or Country csv file as input file however it has some other columns than CIDR? 2) And other columns will be copied in output file too?

**Comment by nimasdj** [comment]
@oschwald sorry I am still waiting for your answer, does it recognize GeoIp2 City csv as input file or only binary database? And if it recognizes GeoIp2 csv file too will this converter copy other fields in output csv file too?

**Comment by oschwald** [comment]
Please direct your questions to [support@maxmind.com](mailto:support@maxmind.com).
