### ISSUE TITLE
File Buffer only seems to be released after the end of programs execution.

### ISSUE THREAD

**Issue by orang3-juic3** [maxmind/geoip2-csv-converter#30]
I am making a program with java that uses this utility and currently I cannot time my tasks properly because the buffer seems to be release a while after the end of execution.

**Comment by oschwald** [comment]
I am a bit confused about the change you are requesting. This program closes the files when it finishes processing the files, which is immediately before it exits. Whether the file is immediately available to another program probably depends on the specifics of your operating system. Perhaps you are asking for fsync to be called before closing the file, although that will just flush the file to disk.

If you could provide more details as well as information on your operating system, that would be useful.

**Comment by orang3-juic3** [comment]
Hey, I am writing my program with Java utilising the Runtime.getRuntime().exec() function to execute a command with the oses command line interpreter, just like a casual user would do it if they opened their command line interpreter on their own. I'm currently writing my program for Windows 10 and so am using the Windows 10 exe, however I plan on making a version for linux.
> Perhaps you are asking for fsync to be called before closing the file, although that will just flush the file to disk.
I feel like this could a solution

Thank you for your time.

**Comment by oschwald** [comment]
What is the actual issue you are experiencing? Is it that you can open the file but it isn't fully written? Or is it that Windows says that the file is in use by another program? If it is the latter, I am not sure calling sync will help significantly. It might help some of the time, but you might be best off just waiting until the file becomes available.

**Comment by orang3-juic3** [comment]
Windows says the file is in use by another program. How could I definitively know whether the file is available? Checking the size made it so the data wouldn't be written to the file at all. 

Thank you for your time.

**Comment by oschwald** [comment]
1.2.0 has been released with the sync change. As I mentioned, I am not convinced it will always work in your particular case. Probably the easiest way to check if it is available is to try using it and if it fails due to that particular reason, retrying.
