### ISSUE TITLE
Can't run the executable file to change ip representation from cidr to range

### ISSUE THREAD

**Issue by AK-1996** [maxmind/geoip2-csv-converter#34]
As I wrote in Title i have a problem to change the network column format of GeoLite2-City-Blocks-IPv4.csv database from cidr to range type.
I'm using a macOS Big Sur version 11.0.1 and i downloaded the 'geoip2-csv-converter-v1.3.0-linux-amd64.tar.gz' zipped file from the releases page of github (https://github.com/maxmind/geoip2-csv-converter/releases). After that i unzipped the file and moved to the folder in the same directory where i keep the database file, then from Terminal i went inside geoip2-csv-converter-v1.3.0 directory and tried to run the following command:

./geoip2-csv-converter -block-file=GeoLite2-City-Blocks-IPv4.csv -output-file=new_GeoLite2-City-Blocks-IPv4.csv -include-integer-range

but i got the following error: 
zsh: exec format error: ./geoip2-csv-converter

Does anyone know where i am wrong with this or do you know how can i solve my problem?

**Comment by oschwald** [comment]
You need the `darwin` binary, not `linux`.

**Comment by AK-1996** [comment]
> You need the `darwin` binary, not `linux`.

Thank you! I didn't understand 'darwin' was for macOS systems
