### ISSUE TITLE
error reading CSV header: EOF when -block-file is the same as -output-file

### ISSUE THREAD

**Issue by OlyRice** [maxmind/geoip2-csv-converter#36]
I have the converter in the same folder as the csv files and I am using 

> geoip2-csv-converter-v1.3.0-darwin-amd64.tar.gz
> 1.39 MB

I run with the following 

`./geoip2-csv-converter -block-file GeoLite2-Country-Blocks-IPv6.csv -include-hex-range -output-file GeoLite2-Country-Blocks-IPv6.csv`

however I am getting a return of error reading CSV header: EOF whenever I run the above.

**Comment by oschwald** [comment]
Does it work if your input file is different than your output file? It doesn't read the whole file into memory first so I expect that it is being truncated before it gets read.

**Comment by OlyRice** [comment]
I have tried with the following and Im still getting the same output 

`./geoip2-csv-converter -block-file GeoLite2-Country-Blocks-IPv6.csv -include-hex-range -output-file GeoLite2-Country-Blocks-IPv6-edit.csv`


> Error: error reading CSV header: EOF

**Comment by oschwald** [comment]
Have you confirmed that `GeoLite2-Country-Blocks-IPv6.csv` has data in it? If you ran the original command, it is likely the file was truncated.

**Comment by OlyRice** [comment]
Thanks that seems to be the issue, the file was empty. Feel stupid I never checked it, thanks again.

**Comment by oschwald** [comment]
I'll leave this open as it would make sense for us to add a check for this to prevent confusion the future.

**Comment by oschwald** [comment]
The tool now returns an error if the input and output files are the same.
