### ISSUE TITLE
"Error: invalid CIDR address: 16777216"

### ISSUE THREAD

**Issue by joacim-boive** [maxmind/geoip2-csv-converter#8]
./geoip2-csv-converter -include-range -block-file=GeoLiteCity-Blocks.csv -output-file=blocks.csv

To be able to run it at all I had to remove your copyright line using:
sed -i '' 1d GeoLiteCity-Blocks.csv

What am I missing?

**Comment by oschwald** [comment]
This program only works on GeoIP2 or GeoLite2 CSV files. It appears that you are trying to use a legacy file.

**Comment by joacim-boive** [comment]
Aha! I must have downloaded the wrong one - because I retraced my steps and now it looks better. :)
